### ISSUE TITLE
Incorrect details shown on browse page on navigating from search page

### ISSUE THREAD

**Issue by anandrajaram21** [the-rarbg/yaps#11]
Clicking the TV Show button (or any button for that matter) navigates to the browse page and shows the wrong data
![image](https://github.com/the-rarbg/yaps/assets/48560219/f0087e4f-3e05-4130-9d0e-12e6ab055c29)
![image](https://github.com/the-rarbg/yaps/assets/48560219/3f0bfec7-1647-426b-bc1d-719bfe04bfca)

**Comment by the-rarbg** [comment]
thanks for reporting

**Comment by payme-pramod** [comment]
Fixed
