### ISSUE TITLE
Hover Effect

### ISSUE THREAD

**Issue by the-rarbg** [the-rarbg/yaps#15]
Create good effect on hover

**Comment by arey-pranay** [comment]
Tried overwriting the card-hover-animation, but it has an issue. Some elements tend to get a thin red top and left border around them in their normal state. I think it's for specifically the elements with even IDs (maybe), any idea what property might be conflicting?

https://github.com/the-rarbg/yaps/assets/86497126/4bde9c5c-f49a-49e4-84ce-459ed93286d5

**Comment by gmallios** [comment]
I changed the hover effect and opened a PR, what are your thoughts? Some shadows could be added to improve the effect.

https://github.com/the-rarbg/yaps/assets/44323649/d90e33e2-f095-4649-b657-2378d32f8a12

**Comment by Ekaiva** [comment]
fixed
