### ISSUE TITLE
Thumbnail quality

### ISSUE THREAD

**Issue by Mntz** [the-rarbg/yaps#22]
The site is currently using very high resolution images for thumbnails which is increasing the size of the pages and bad for image quality (too crisp/pixelated look because of high resize).

Instead of using this:
 https://image.tmdb.org/t/p/original//4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg
Use this:
 https://image.tmdb.org/t/p/w500//4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg
Comparison:
 [https://i.imgur.com/OdIjWrU.jpeg](https://i.imgur.com/OdIjWrU.jpeghttps://i.imgur.com/OdIjWrU.jpeg)

Thanks and keep up the amazing work!

**Comment by the-rarbg** [comment]
make sense
