### ISSUE TITLE
Sidebar Icons Messed Up

### ISSUE THREAD

**Issue by arey-pranay** [the-rarbg/yaps#23]
When I opened the site on my laptop, there were a couple of issues:

1) The FAQs icon was not visible
2) The remaining icons in the sidebar/navbar were collapsing into each other

PS: The sidebar also had a very low mt which made it look kinda weird.

Observed Behavior:

![image](https://github.com/the-rarbg/yaps/assets/86497126/585e2798-06ef-4056-a83c-68b4a3604571)

Expected Behavior:

![image](https://github.com/the-rarbg/yaps/assets/86497126/97bce1cb-9e1b-480d-a6f5-4fe760612ad7)

But when I checked the issues on GitHub there was no such issue, so I decided to create as well as solve it. I hope you guys find it useful. All suggestions are welcome, just wanna help. 

Thank You..

**Comment by the-rarbg** [comment]
great
