### ISSUE TITLE
White black schema toggle

### ISSUE THREAD

**Issue by the-rarbg** [the-rarbg/yaps#6]
could you add a toggle for light mode on the site? for some reason the colors between the background and the UI is hard for me to read, or maybe make the UI buttons brighter or something, personally I think this site is where most of the time should be spent, thergb site looks kinda sketch, it just "looks" off, I think it is a better idea to continue with your unique site, instead of recreating something others have recreated and spamming malware, people would be warry because of how similar they look

**Comment by Mennaruuk** [comment]
I'm confused. Aren't you the owner of this repo!?

**Comment by the-rarbg** [comment]
ha ha copied same from r/piracy user, so to have context

**Comment by Ekaiva** [comment]
fixed
