### ISSUE TITLE
Magnet download problem

### ISSUE THREAD

**Issue by tso33** [the-rarbg/yaps#76]
Hello,

Downloading by clicking to magnet, download doesn't start.

There is a difference on links between original site and yaps

Thank you

**Comment by the-rarbg** [comment]
can you share magnet link or the page link

**Comment by tso33** [comment]
Sorry I can't add a link.

But you can find a random item on both therarbg.com and yaps.cc and compare the magnet links... They are completely different and yaps magnet link doesn't work.

Thank you

**Comment by tso33** [comment]
I found that yaps magnet missing the &tr= after the name and before each tracker... So all the trackers shows as name of download and actual trackers are zero... Also instead of udp%3A%2F%2F, yaps link has udp://. That's the difference between the two magnet links wasp and original site.

**Comment by tso33** [comment]
any news?

**Comment by the-rarbg** [comment]
fixed by someone
