### ISSUE TITLE
Server Not Found 

### ISSUE THREAD

**Issue by IamNickerson** [the-rarbg/yaps#79]
It seems the page is unable to load and it is showing the error Server Not Found

![image](https://github.com/the-rarbg/yaps/assets/61643704/02f34ab5-6f43-4500-9eb2-3a2f38800f4c)

The Browser I use is Firefox.

**Comment by the-rarbg** [comment]
sorry for delay, but fixed now

**Comment by IamNickerson** [comment]
Bro
![image](https://github.com/the-rarbg/yaps/assets/61643704/b71490e8-5183-4a78-b088-cd3a36cf447d)

**Comment by the-rarbg** [comment]
oh my bad, fixed now

**Comment by IamNickerson** [comment]
Alright fixed 
![image](https://github.com/the-rarbg/yaps/assets/61643704/276bc3be-eff4-4f3f-8fe7-d8509e02f83c)
