### ISSUE TITLE
Movie Page not loading up

### ISSUE THREAD

**Issue by IamNickerson** [the-rarbg/yaps#80]
When I try to click on a movie to watch its not showing the details instead shows a 0 and nothing

![image](https://github.com/the-rarbg/yaps/assets/61643704/534cb2f6-bb5c-4036-a896-69c2906fb312)

**Comment by rcl-viveksharma** [comment]
yes it

**Comment by rcl-viveksharma** [comment]
oh seems fine now

**Comment by the-rarbg** [comment]
done
